-- Create table for school demo requests
CREATE TABLE IF NOT EXISTS public.school_demo_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    school_name TEXT NOT NULL,
    role TEXT NOT NULL,
    student_count TEXT,
    message TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS school_demo_requests_email_idx ON public.school_demo_requests(email);

-- Create index on status for faster filtering
CREATE INDEX IF NOT EXISTS school_demo_requests_status_idx ON public.school_demo_requests(status);

-- Create RLS policies
ALTER TABLE public.school_demo_requests ENABLE ROW LEVEL SECURITY;

-- Allow admins to see all requests
CREATE POLICY "Allow admins to manage demo requests" ON public.school_demo_requests
    FOR ALL
    TO authenticated
    USING (auth.jwt() ->> 'role' = 'admin')
    WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- Allow anonymous users to insert new requests
CREATE POLICY "Allow anonymous users to submit demo requests" ON public.school_demo_requests
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- Add table to realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE school_demo_requests;